name: Generative AI Demo
run-name: Requirements Update
on: [push]
jobs:
  Workflow-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install packages
        run: |
          python -m pip install poetry
          poetry install

      - name: Perform extraction on Cameo model
        run: python components/extract_requirements.py

      - name: Perform extraction on 3DX model
        run: python components/extract_parameters.py

