name: Generative AI Demo
run-name: Requirements Update
on: [push]
jobs:
  Workflow-Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Requirements Update"
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install packages
        run: |
          pip install poetry
          poetry install
      - run: echo "Listing Directory"
      - name: List Repository Files
        run: ls -lR
      - run: echo "*** Done ***"
