name: install
run-name: Workflow Setup
on:
  workflow_call:
jobs:
  Workflow-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install packages
        run: |
          python -m pip install poetry
          poetry install

